[package]
name = "journal-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
serenity = "0.12.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
